from pathlib import Path
import sys
import pandas as pd

# ---------------------------------------------------------------------
# Project root
# ---------------------------------------------------------------------
ROOT = Path(__file__).resolve().parent

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

# ---------------------------------------------------------------------
# Import existing backtest functions
# ---------------------------------------------------------------------
from src.portfolio.backtest import run_backtest, save_backtest_results


# ---------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------
DATA_DIR = ROOT / "data" / "processed"
PRED_DIR = ROOT / "experiments"
OUT_DIR = ROOT / "backtests"

ASSETS = [
    "BTC",
    "ETH",
    "XRP",
    "ADA",
    "DOGE",
    "DOT",
    "LTC",
]

# Transaction costs to test
# 0.001 = 0.10%
TRANSACTION_COSTS = [
    0.0000,   # 0.00%
    0.0005,   # 0.05%
    0.0010,   # 0.10%
    0.0025,   # 0.25%
    0.0050,   # 0.50%
    0.0100,   # 1.00%
]

# Main strategies
STRATEGIES = [
    "paper_binary",
    "probability",
]

# Rebalancing frequencies
REBALANCE_FREQUENCIES = [
    7,
    30,
]

# Same settings used in the main portfolio experiment
COVARIANCE_WINDOW = 90
PHI = 0.50

# Prediction file generated by run_baseline.py
PREDICTION_SUFFIX = "_market_trends_predictions_1d.csv"


# ---------------------------------------------------------------------
# Load market prices
# ---------------------------------------------------------------------
def load_prices():
    price_frames = []

    for asset in ASSETS:
        path = DATA_DIR / f"{asset}_features.parquet"

        if not path.exists():
            raise FileNotFoundError(
                f"Missing market data file:\n{path}"
            )

        df = pd.read_parquet(path)

        if "timestamp" not in df.columns:
            raise ValueError(
                f"{path} does not contain a 'timestamp' column."
            )

        if "close" not in df.columns:
            raise ValueError(
                f"{path} does not contain a 'close' column."
            )

        df["timestamp"] = pd.to_datetime(df["timestamp"])
        df = df[["timestamp", "close"]].copy()

        df = df.rename(columns={"close": asset})
        df = df.set_index("timestamp")

        price_frames.append(df)

    prices = pd.concat(price_frames, axis=1)
    prices = prices.sort_index()
    prices = prices.dropna()

    print(
        f"Loaded price data: {prices.shape[0]} dates × "
        f"{prices.shape[1]} assets"
    )

    return prices


# ---------------------------------------------------------------------
# Load model predictions
# ---------------------------------------------------------------------
def load_predictions():
    prediction_frames = []

    for asset in ASSETS:
        path = PRED_DIR / f"{asset}{PREDICTION_SUFFIX}"

        if not path.exists():
            raise FileNotFoundError(
                f"Missing prediction file:\n{path}"
            )

        df = pd.read_csv(path)

        required_columns = [
            "timestamp",
            "prediction",
            "prob_positive",
        ]

        missing = [
            col for col in required_columns
            if col not in df.columns
        ]

        if missing:
            raise ValueError(
                f"{path} is missing columns: {missing}"
            )

        df["timestamp"] = pd.to_datetime(df["timestamp"])

        df = df[
            [
                "timestamp",
                "prediction",
                "prob_positive",
            ]
        ].copy()

        df["asset"] = asset

        prediction_frames.append(df)

    predictions = pd.concat(
        prediction_frames,
        ignore_index=True,
    )

    predictions = predictions.sort_values(
        ["timestamp", "asset"]
    ).reset_index(drop=True)

    print(
        f"Loaded predictions: {len(predictions)} rows"
    )

    return predictions


# ---------------------------------------------------------------------
# Main experiment
# ---------------------------------------------------------------------
def main():

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    prices = load_prices()
    predictions = load_predictions()

    all_results = []

    total_runs = (
        len(TRANSACTION_COSTS)
        * len(STRATEGIES)
        * len(REBALANCE_FREQUENCIES)
    )

    run_number = 0

    print()
    print("=" * 75)
    print("CRYPTO TRACK - TRANSACTION COST SENSITIVITY")
    print("=" * 75)
    print(f"Transaction costs: {TRANSACTION_COSTS}")
    print(f"Strategies: {STRATEGIES}")
    print(f"Rebalance frequencies: {REBALANCE_FREQUENCIES}")
    print(f"Total experiments: {total_runs}")
    print("=" * 75)
    print()

    # ---------------------------------------------------------------
    # Run experiments
    # ---------------------------------------------------------------
    for transaction_cost in TRANSACTION_COSTS:

        for strategy in STRATEGIES:

            for rebalance_frequency in REBALANCE_FREQUENCIES:

                run_number += 1

                cost_percent = transaction_cost * 100

                print(
                    f"[{run_number}/{total_runs}] "
                    f"{strategy} | "
                    f"rebalance={rebalance_frequency}d | "
                    f"cost={cost_percent:.2f}%"
                )

                result = run_backtest(
                    prices=prices,
                    predictions=predictions,
                    strategy=strategy,
                    transaction_cost=transaction_cost,
                    rebalance_frequency=rebalance_frequency,
                    covariance_window=COVARIANCE_WINDOW,
                    probability_column="prob_positive",
                    phi=PHI,
                )

                # ---------------------------------------------------
                # Save detailed daily backtest
                # ---------------------------------------------------
                filename = (
                    f"{strategy}"
                    f"_cost_{transaction_cost:.4f}"
                    f"_rebalance_{rebalance_frequency}d.csv"
                )

                detailed_path = OUT_DIR / filename

                save_backtest_results(
                    result,
                    detailed_path,
                )

                # ---------------------------------------------------
                # Extract summary metrics
                # ---------------------------------------------------
                metrics = result["metrics"].copy()

                metrics["strategy"] = strategy
                metrics["transaction_cost"] = transaction_cost
                metrics["transaction_cost_percent"] = cost_percent
                metrics["rebalance_frequency"] = rebalance_frequency
                metrics["phi"] = PHI

                all_results.append(metrics)

                print(
                    f"    Cumulative Return: "
                    f"{metrics.get('cumulative_return', float('nan')):.2%}"
                )

                print(
                    f"    Annualized Return: "
                    f"{metrics.get('annualized_return', float('nan')):.2%}"
                )

                print(
                    f"    Sharpe: "
                    f"{metrics.get('sharpe', float('nan')):.4f}"
                )

                print(
                    f"    Turnover: "
                    f"{metrics.get('average_turnover', float('nan')):.4f}"
                )

                print(
                    f"    Total Costs: "
                    f"{metrics.get('total_transaction_cost', float('nan')):.4f}"
                )

                print()

    # -----------------------------------------------------------------
    # Combine results
    # -----------------------------------------------------------------
    results_df = pd.DataFrame(all_results)

    # Put important columns first
    preferred_columns = [
        "strategy",
        "transaction_cost",
        "transaction_cost_percent",
        "rebalance_frequency",
        "phi",
        "cumulative_return",
        "annualized_return",
        "annualized_volatility",
        "sharpe",
        "sortino",
        "max_drawdown",
        "average_turnover",
        "total_transaction_cost",
    ]

    existing_columns = [
        col for col in preferred_columns
        if col in results_df.columns
    ]

    remaining_columns = [
        col for col in results_df.columns
        if col not in existing_columns
    ]

    results_df = results_df[
        existing_columns + remaining_columns
    ]

    # Sort for easier analysis
    results_df = results_df.sort_values(
        [
            "strategy",
            "rebalance_frequency",
            "transaction_cost",
        ]
    ).reset_index(drop=True)

    # -----------------------------------------------------------------
    # Save experiment summary
    # -----------------------------------------------------------------
    output_path = (
        ROOT
        / "experiments"
        / "transaction_cost_sensitivity.csv"
    )

    results_df.to_csv(
        output_path,
        index=False,
    )

    print("=" * 75)
    print("EXPERIMENT COMPLETE")
    print("=" * 75)

    print(
        f"Saved summary:\n{output_path}"
    )

    print()
    print("Summary:")
    print()

    display_columns = [
        "strategy",
        "transaction_cost_percent",
        "rebalance_frequency",
        "cumulative_return",
        "annualized_return",
        "sharpe",
        "sortino",
        "max_drawdown",
        "average_turnover",
        "total_transaction_cost",
    ]

    display_columns = [
        col for col in display_columns
        if col in results_df.columns
    ]

    print(
        results_df[display_columns].to_string(
            index=False
        )
    )

    print()
    print(
        "Output files have been saved in:"
    )
    print(f"  {OUT_DIR}")
    print()
    print(
        "Main summary:"
    )
    print(f"  {output_path}")


if __name__ == "__main__":
    main()